### ISSUE TITLE
error compiling index.ts

### ISSUE THREAD

**Issue by gcd445** [open-voip-alliance/WebphoneLib#26]
### Version

0.2.0

### File / Feature

{file or feature containing the issue}

### Expected behaviour

{what should happen}

### Actual behaviour

{what happens}

### Stacktrace / Error message
```
src/index.ts → dist/index.mjs...
[!] (plugin rpt2) Error: D:/g/dev/WebphoneLib/src/transport.ts(227,23): semantic error TS2339:
Property 'removeAllListeners' does not exist on type 'Transport'.
src\transport.ts
Error: D:/g/dev/WebphoneLib/src/transport.ts(227,23): semantic error TS2339: Property 'removeAllListeners' does not exist on type 'Transport'.
    at error (D:\g\dev\WebphoneLib\node_modules\rollup\dist\rollup.js:5363:30)
    at throwPluginError (D:\g\dev\WebphoneLib\node_modules\rollup\dist\rollup.js:11716:12)
    at Object.error (D:\g\dev\WebphoneLib\node_modules\rollup\dist\rollup.js:12685:24)
    at Object.error (D:\g\dev\WebphoneLib\node_modules\rollup\dist\rollup.js:11915:38)
    at RollupContext.error (D:\g\dev\WebphoneLib\node_modules\rollup-plugin-typescript2\src\rollupcontext.ts:37:18)
    at D:\g\dev\WebphoneLib\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:41:11
    at arrayEach (D:\g\dev\WebphoneLib\node_modules\rollup-plugin-typescript2\node_modules\lodash\lodash.js:516:11)
    at forEach (D:\g\dev\WebphoneLib\node_modules\rollup-plugin-typescript2\node_modules\lodash\lodash.js:9342:14)
    at _.each (D:\g\dev\WebphoneLib\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:9:2)
    at Object.transform (D:\g\dev\WebphoneLib\node_modules\rollup-plugin-typescript2\src\index.ts:235:5)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webphone-lib@0.1.9 build: `npm run clean && rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webphone-lib@0.1.9 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     d:\node\npm-cache\_logs\2019-12-05T00_47_07_685Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webphone-lib@0.1.9 prepare: `npm run lint && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webphone-lib@0.1.9 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Other info

{anything else that might be related/useful}

**Comment by confususs** [comment]
Thanks for making an issue! I'm not sure how to recreate the problem you have, could you tell me what you are doing to get the output you shared?

**Comment by gcd445** [comment]
Hi confususs , it must have been when I updated all the packages by using ncu, I cloned a new copy and npm install was successful, except for the tslint ERROR: src/media.ts:8:1 - Import sources within a group must be alphabetized. But it was easily fixed by moving it up 3 lines

**Comment by confususs** [comment]
Great that you managed to get it working! I'll fix the tslint sometime soon.
