### ISSUE TITLE
TypeError: Cannot read property 'localStream' and 'remoteStream' of undefined

### ISSUE THREAD

**Issue by patrickswijgman** [open-voip-alliance/WebphoneLib#35]
### Version

Version 0.2.7

### Actual behaviour

`'TypeError: Cannot read property \'localStream\' of undefined
    at Wt.setInput (https://webphone.voys.nl/webphone-lib.mjs:15:262599)'
`

`'TypeError: Cannot read property \'remoteStream\' of undefined
    at Wt.setOutput (https://webphone.voys.nl/webphone-lib.mjs:15:262995)'`

See logs below

### Stacktrace / Error message

```
19 Feb 2020 11:06:44.304145.128.201.25, 127.0.0.1, 157.230.120.63 INFO timestamp='2020-02-19T10:06:44.279Z' trace=p2in1ype level=info module=media message='media devices changed'
19 Feb 2020 11:06:44.306145.128.201.25, 127.0.0.1, 157.230.120.63 INFO timestamp='2020-02-19T10:06:44.283Z' trace=p2in1ype level=info module=media message='undefined device for headsetOutput'
19 Feb 2020 11:06:44.307145.128.201.25, 127.0.0.1, 157.230.120.63 INFO timestamp='2020-02-19T10:06:44.281Z' trace=p2in1ype level=info module=media message='preferred device found for headsetInput:' context.0='Logitech USB Headset (046d:0a45)'
19 Feb 2020 11:06:44.435145.128.201.25, 127.0.0.1, 157.230.120.63 INFO timestamp='2020-02-19T10:06:44.287Z' trace=p2in1ype level=info module=media message='undefined device for ringtoneOutput'
19 Feb 2020 11:06:44.558145.128.201.25, 127.0.0.1, 157.230.120.63 DEBUG timestamp='2020-02-19T10:06:44.414Z' trace=p2in1ype level=debug module='web-calling' message='media: Requesting input stream with: audioProcessing=true'
19 Feb 2020 11:06:44.558145.128.201.25, 127.0.0.1, 157.230.120.63 DEBUG timestamp='2020-02-19T10:06:44.414Z' trace=p2in1ype level=debug module='web-calling' message='media: Using input constraints: {"audio":{"echoCancellation":true,"noiseSuppression":true,"autoGainControl":true,"googAudioMirroring":true,"googAutoGainControl":true,"googAutoGainControl2":true,"googEchoCancellation":true,"googHighpassFilter":true,"googNoiseSuppression":true,"googTypingNoiseDetection":true,"deviceId":"62a27e95a3af6430f3ce15a7fcb9ddd3edfb6ad5722b1404f578b308a882c847"},"video":false}'
19 Feb 2020 11:06:44.558145.128.201.25, 127.0.0.1, 157.230.120.63 INFO timestamp='2020-02-19T10:06:44.415Z' trace=p2in1ype level=info module=media message='(preferred) headset output not found, reverting back to default'
19 Feb 2020 11:06:44.570145.128.201.25, 127.0.0.1, 157.230.120.63 DEBUG timestamp='2020-02-19T10:06:44.437Z' trace=p2in1ype level=debug module='web-calling' message='media: Media stream track has settings: {"autoGainControl":true,"channelCount":1,"deviceId":"62a27e95a3af6430f3ce15a7fcb9ddd3edfb6ad5722b1404f578b308a882c847","echoCancellation":true,"groupId":"a4737f1698de740fb0ad87e78f39be882aa31059397458d6650899246d868b72","latency":0.01,"noiseSuppression":true,"sampleRate":48000,"sampleSize":16}'
19 Feb 2020 11:06:44.572145.128.201.25, 127.0.0.1, 157.230.120.63 ERROR timestamp='2020-02-19T10:06:44.446Z' trace=p2in1ype level=error module=error message='TypeError: Cannot read property \'localStream\' of undefined
    at Wt.setInput (https://webphone.voys.nl/webphone-lib.mjs:15:262599)'
19 Feb 2020 11:06:44.733145.128.201.25, 127.0.0.1, 157.230.120.63 ERROR timestamp='2020-02-19T10:06:44.546Z' trace=p2in1ype level=error module=error message='TypeError: Cannot read property \'remoteStream\' of undefined
    at Wt.setOutput (https://webphone.voys.nl/webphone-lib.mjs:15:262995)'
19 Feb 2020 11:06:44.735145.128.201.25, 127.0.0.1, 157.230.120.63 INFO timestamp='2020-02-19T10:06:44.539Z' trace=p2in1ype level=info module=media message='(preferred) ringtone output not found, reverting back to default'
19 Feb 2020 11:06:44.744145.128.201.25, 127.0.0.1, 157.230.120.63 INFO timestamp='2020-02-19T10:06:44.717Z' trace=p2in1ype level=info module=toasts message='showing toast with id: 3 and title: Headsetverbinding verbroken'
19 Feb 2020 11:06:44.744145.128.201.25, 127.0.0.1, 157.230.120.63 INFO timestamp='2020-02-19T10:06:44.718Z' trace=p2in1ype level=info module=toasts message='showing toast with id: 4 and title: Headsetverbinding verbroken'
19 Feb 2020 11:06:44.748145.128.201.25, 127.0.0.1, 157.230.120.63 INFO timestamp='2020-02-19T10:06:44.718Z' trace=p2in1ype level=info module=toasts message='showing toast with id: 5 and title: Microfoon (opnieuw) verbonden'
19 Feb 2020 11:06:46.348145.128.201.25, 127.0.0.1, 157.230.120.63 DEBUG timestamp='2020-02-19T10:06:46.301Z' trace=p2in1ype level=debug module='web-calling' message='sip.invitation: Invitation.accept'
19 Feb 2020 11:06:46.350145.128.201.25, 127.0.0.1, 157.230.120.63 DEBUG timestamp='2020-02-19T10:06:46.302Z' trace=p2in1ype level=debug module='web-calling' message='sip.sessionDescriptionHandler: initPeerConnection'
19 Feb 2020 11:06:46.351145.128.201.25, 127.0.0.1, 157.230.120.63 DEBUG timestamp='2020-02-19T10:06:46.301Z' trace=p2in1ype level=debug module='web-calling' message='sip.invitation: Session 5a3b7b8f4b69987e3e931aaa4d12fbbf@voipgrid.nlas25bd052b transitioned to state Establishing'
19 Feb 2020 11:06:46.353145.128.201.25, 127.0.0.1, 157.230.120.63 DEBUG timestamp='2020-02-19T10:06:46.302Z' trace=p2in1ype level=debug module='web-calling' message='sip.sessionDescriptionHandler: SessionDescriptionHandlerOptions: {"alwaysAcquireMediaFirst":false,"constraints":{"audio":true,"video":false},"modifiers":[null],"peerConnectionOptions":{"rtcConfiguration":{"iceServers":[]}}}'
19 Feb 2020 11:06:46.355145.128.201.25, 127.0.0.1, 157.230.120.63 DEBUG timestamp='2020-02-19T10:06:46.302Z' trace=p2in1ype level=debug module='web-calling' message='sip.sessionDescriptionHandler: New peer connection created'
19 Feb 2020 11:06:46.356145.128.201.25, 127.0.0.1, 157.230.120.63 DEBUG timestamp='2020-02-19T10:06:46.303Z' trace=p2in1ype level=debug module='web-calling' message='sessionDescriptionHandlerFactory: Returning patched SDH for session[object Object]'
19 Feb 2020 11:06:46.356145.128.201.25, 127.0.0.1, 157.230.120.63 DEBUG timestamp='2020-02-19T10:06:46.306Z' trace=p2in1ype level=debug module='web-calling' message='sip.sessionDescriptionHandler: track added'
19 Feb 2020 11:06:46.358145.128.201.25, 127.0.0.1, 157.230.120.63 DEBUG timestamp='2020-02-19T10:06:46.308Z' trace=p2in1ype level=debug module='web-calling' message='media: Requesting input stream with: audioProcessing=true'
19 Feb 2020 11:06:46.360145.128.201.25, 127.0.0.1, 157.230.120.63 DEBUG timestamp='2020-02-19T10:06:46.308Z' trace=p2in1ype level=debug module='web-calling' message='sip.sessionDescriptionHandler: acquiring local media'
19 Feb 2020 11:06:46.360145.128.201.25, 127.0.0.1, 157.230.120.63 DEBUG timestamp='2020-02-19T10:06:46.308Z' trace=p2in1ype level=debug module='web-calling' message='media: Using input constraints: {"audio":{"echoCancellation":true,"noiseSuppression":true,"autoGainControl":true,"googAudioMirroring":true,"googAutoGainControl":true,"googAutoGainControl2":true,"googEchoCancellation":true,"googHighpassFilter":true,"googNoiseSuppression":true,"googTypingNoiseDetection":true,"deviceId":"default"},"video":false}'
19 Feb 2020 11:06:46.377145.128.201.25, 127.0.0.1, 157.230.120.63 DEBUG timestamp='2020-02-19T10:06:46.340Z' trace=p2in1ype level=debug module='web-calling' message='media: Media stream track has settings: {"autoGainControl":true,"channelCount":1,"deviceId":"default","echoCancellation":true,"groupId":"9a1fb6a1c60318d7184a527199052d21f30c5d9a7e066c5f8d4561f3e33454f3","latency":0.01,"noiseSuppression":true,"sampleRate":48000,"sampleSize":16}'
19 Feb 2020 11:06:46.381145.128.201.25, 127.0.0.1, 157.230.120.63 DEBUG timestamp='2020-02-19T10:06:46.342Z' trace=p2in1ype level=debug module='web-calling' message='sip.sessionDescriptionHandler: unable to acquire streams'
19 Feb 2020 11:06:46.392145.128.201.25, 127.0.0.1, 157.230.120.63 DEBUG timestamp='2020-02-19T10:06:46.343Z' trace=p2in1ype level=debug module='web-calling' message='sip.sessionDescriptionHandler: TypeError: Cannot read property \'disconnect\' of undefined'
19 Feb 2020 11:06:46.392145.128.201.25, 127.0.0.1, 157.230.120.63 DEBUG timestamp='2020-02-19T10:06:46.343Z' trace=p2in1ype level=debug module='web-calling' message='sip.invitation: Session.setOfferAndGetAnswer: SDH setDescription or getDescription rejected...'
19 Feb 2020 11:06:46.416145.128.201.25, 127.0.0.1, 157.230.120.63 DEBUG timestamp='2020-02-19T10:06:46.345Z' trace=p2in1ype level=debug module='web-calling' message='sip.invitation: TypeError: Cannot read property \'disconnect\' of undefined'
19 Feb 2020 11:06:46.416145.128.201.25, 127.0.0.1, 157.230.120.63 DEBUG timestamp='2020-02-19T10:06:46.345Z' trace=p2in1ype level=debug module='web-calling' message='sip.invitation: unable to acquire streams'
19 Feb 2020 11:06:46.417145.128.201.25, 127.0.0.1, 157.230.120.63 DEBUG timestamp='2020-02-19T10:06:46.345Z' trace=p2in1ype level=debug module='web-calling' message='sip.transaction.ist: State change to "Completed" on INVITE server transaction with id z9hG4bKce48.c7505015.0.'
19 Feb 2020 11:06:46.417145.128.201.25, 127.0.0.1, 157.230.120.63 DEBUG timestamp='2020-02-19T10:06:46.344Z' trace=p2in1ype level=debug module='web-calling' message='sip.invitation: unable to acquire streams'
```

**Comment by confususs** [comment]
I think to fix this we should not allow users to change the audio device if the call has not been accepted yet.
